name: patota_app
description: A new Flutter project.
version: 1.0.3
publish_to: none

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.1.3
  cloud_firestore: ^4.1.0
  firebase_core: ^2.3.0
  firebase_database: ^10.3.6
  lints: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/icons/
    - assets/images/logo/
  fonts:
  - family: AppIcons
    fonts:
      - asset: assets/images/icons/AppIcons.ttf

